import { escapeHtml } from "./utils.js";

const iconLabels = { header: "ID", summary: "RE", experience: "EX", education: "FO", courses: "CU", certifications: "CE", projects: "PR", languages: "ID", skills: "HA" };

const itemFields = {
  experience: [["title", "Cargo"], ["organization", "Empresa"], ["city", "Cidade"], ["state", "Estado"], ["country", "País"], ["remote", "Trabalho remoto", "checkbox"], ["start", "Início (mês/ano)", "month"], ["end", "Término (mês/ano)", "month"], ["current", "Trabalho atual", "checkbox"], ["technologies", "Tecnologias (separadas por vírgula)"], ["projectLink", "Link do projeto"], ["description", "Descrição", "textarea"], ["activities", "Atividades (uma por linha)", "textarea"]],
  education: [["title", "Curso ou formação"], ["degree", "Grau"], ["organization", "Instituição"], ["city", "Cidade"], ["state", "Estado"], ["country", "País"], ["start", "Início (mês/ano)", "month"], ["end", "Conclusão (mês/ano)", "month"], ["current", "Em andamento", "checkbox"], ["certificate", "Certificado"], ["link", "Link"], ["description", "Descrição", "textarea"]],
  courses: [["title", "Nome do curso"], ["organization", "Instituição ou plataforma"], ["hours", "Carga horária"], ["date", "Data", "month"], ["certificate", "Certificado"], ["link", "Link"], ["description", "Descrição", "textarea"]],
  certifications: [["title", "Nome da certificação"], ["organization", "Instituição emissora"], ["issued", "Emissão", "month"], ["expires", "Validade", "month"], ["noExpiry", "Sem validade", "checkbox"], ["credential", "Código da credencial"], ["credentialLink", "Link da credencial"], ["description", "Descrição", "textarea"]],
  projects: [["title", "Nome do projeto"], ["technologies", "Tecnologias (separadas por vírgula)"], ["github", "GitHub"], ["site", "Site"], ["date", "Data", "month"], ["team", "Equipe"], ["client", "Cliente"], ["description", "Descrição", "textarea"]],
  languages: [["title", "Idioma"], ["level", "Nível em estrelas"], ["customLevel", "Nível personalizado"], ["certificate", "Certificado"], ["description", "Observações", "textarea"]],
  skills: [["title", "Habilidade"], ["level", "Nível (1 a 5)"], ["category", "Categoria"], ["description", "Descrição", "textarea"]],
  custom: [["title", "Título"], ["organization", "Organização ou subtítulo"], ["period", "Data ou período"], ["description", "Descrição", "textarea"]]
};

function inputFor(section, item, [key, label, kind]) {
  const id = `${section.id}-${item.id}-${key}`;
  const value = escapeHtml(Array.isArray(item[key]) ? item[key].map((entry) => entry.text || entry).join("\n") : item[key] || "");
  return `<div class="field ${kind === "textarea" ? "field--wide" : ""}">
    <label for="${id}">${label}</label>
    ${kind === "checkbox"
      ? `<input id="${id}" type="checkbox" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}" ${item[key] ? "checked" : ""}>`
      : kind === "textarea"
      ? `<textarea id="${id}" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}">${value}</textarea>`
      : kind === "month" ? (() => { const [year = "", month = ""] = String(item[key] || "").split("-"); const months = ["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"]; return `<div class="date-picker"><div class="date-picker__months">${months.map((name, index) => `<button type="button" data-action="select-item-month" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}" data-month="${String(index + 1).padStart(2,"0")}" class="${month === String(index + 1).padStart(2,"0") ? "is-selected" : ""}" ${((key === "end" && item.current)) ? "disabled" : ""}>${name}</button>`).join("")}</div><input id="${id}" class="date-picker__year" inputmode="numeric" placeholder="Ano (ex. 2026)" data-date-year="true" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}" value="${year}" ${((key === "end" && item.current)) ? "disabled" : ""}></div>`; })()
      : section.type === "languages" && key === "level" ? `<select id="${id}" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}"><option value="">Sem estrelas</option>${[1,2,3,4,5].map((level) => `<option value="${level}" ${String(item.level) === String(level) ? "selected" : ""}>${"★".repeat(level)}${"☆".repeat(5 - level)} (${level}/5)</option>`).join("")}</select>`
      : key === "degree" ? `<input id="${id}" list="${id}-options" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}" value="${value}"><datalist id="${id}-options"><option>Ensino Médio</option><option>Técnico</option><option>Tecnólogo</option><option>Bacharelado</option><option>Licenciatura</option><option>Pós-graduação</option><option>MBA</option><option>Mestrado</option><option>Doutorado</option><option>Outro</option></datalist>` : `<input id="${id}" data-section-id="${section.id}" data-item-id="${item.id}" data-item-key="${key}" value="${value}" ${((key === "end" && item.current) || (key === "expires" && item.noExpiry)) ? "disabled" : ""}>`}
  </div>`;
}

function editableItems(section) {
  const fields = itemFields[section.type];
  if (!fields) return "";
  const items = section.items.length ? section.items.map((item, index) => `<article class="item-editor" draggable="true" data-draggable-item="true" data-section-id="${section.id}" data-item-id="${item.id}">
    <div class="item-editor__heading"><strong>${section.type === "experience" ? `Experiência ${index + 1}` : `${section.title} ${index + 1}`}</strong>
      <button type="button" data-action="move-item-up" data-section-id="${section.id}" data-item-id="${item.id}" ${index === 0 ? "disabled" : ""} aria-label="Mover item para cima">↑</button><button type="button" data-action="move-item-down" data-section-id="${section.id}" data-item-id="${item.id}" ${index === section.items.length - 1 ? "disabled" : ""} aria-label="Mover item para baixo">↓</button><button class="icon-button icon-button--danger" type="button" data-action="delete-item" data-section-id="${section.id}" data-item-id="${item.id}" aria-label="Excluir item">Excluir</button></div>
    <div class="item-editor__fields">${fields.map((field) => inputFor(section, item, field)).join("")}</div>${["experience", "education"].includes(section.type) ? `<div class="field"><label>Logotipo (opcional)</label><input type="file" accept="image/*" data-item-image-input data-section-id="${section.id}" data-item-id="${item.id}">${item.logo ? `<button type="button" data-action="remove-item-logo" data-section-id="${section.id}" data-item-id="${item.id}">Remover logotipo</button>` : ""}</div>` : ""}${section.type === "projects" ? `<div class="field"><label>Imagens do projeto (até 3)</label><input type="file" accept="image/*" multiple data-project-images data-section-id="${section.id}" data-item-id="${item.id}"><small>${(item.images || []).length} imagem(ns) adicionada(s)</small></div>` : ""}<details class="item-visibility"><summary>Campos visíveis na prévia</summary>${fields.filter(([key]) => !["title"].includes(key)).map(([key, label]) => `<label><input type="checkbox" data-item-visibility="${key}" data-section-id="${section.id}" data-item-id="${item.id}" ${item.visibleFields?.[key] !== false ? "checked" : ""}> ${label}</label>`).join("")}</details>${activityControls(section, item)}${itemCustomFieldsEditor(section, item)}
  </article>`).join("") : `<p class="empty-editor-state">Nenhum item adicionado ainda.</p>`;
  return `${items}<button class="add-item-button" type="button" data-action="add-item" data-section-id="${section.id}">+ Adicionar ${section.type === "experience" ? "experiência" : "item"}</button>`;
}

function itemCustomFieldsEditor(section, item) {
  const fields = item.customFields || [];
  const rows = fields.map((field, index) => { const control = field.type === "longtext" ? `<textarea data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}" ${field.visible === false ? "disabled" : ""}>${escapeHtml(field.value || "")}</textarea>` : field.type === "checkbox" ? `<input type="checkbox" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}" ${field.value ? "checked" : ""} ${field.visible === false ? "disabled" : ""}>` : `<input type="${field.type || "text"}" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}" value="${escapeHtml(field.value || "")}" ${field.visible === false ? "disabled" : ""}>`; return `<div class="custom-field-editor"><div class="custom-field-editor__top"><label>${escapeHtml(field.label)}</label><span>${escapeHtml(field.type || "text")}</span><button type="button" data-action="move-item-custom-field-up" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}" ${index === 0 ? "disabled" : ""}>↑</button><button type="button" data-action="move-item-custom-field-down" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}" ${index === fields.length - 1 ? "disabled" : ""}>↓</button><button type="button" data-action="duplicate-item-custom-field" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}">Duplicar</button><button type="button" data-action="toggle-item-custom-field" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}">${field.visible === false ? "Exibir" : "Ocultar"}</button><button type="button" class="section-tools__danger" data-action="delete-item-custom-field" data-section-id="${section.id}" data-item-id="${item.id}" data-item-custom-field-id="${field.id}">Excluir</button></div>${control}</div>`; }).join("");
  return `<div class="item-custom-fields"><button type="button" data-action="add-item-custom-field" data-section-id="${section.id}" data-item-id="${item.id}">+ Campo do item</button>${rows}</div>`;
}

function activityControls(section, item) {
  const technologies = Array.isArray(item.technologies) ? item.technologies : String(item.technologies || "").split(",").map((value) => value.trim()).filter(Boolean).map((text, index) => ({ id: `tech-${index}-${text}`, text }));
  const techControls = ["experience", "projects"].includes(section.type) ? `<div class="item-custom-fields"><strong>Tecnologias</strong><div class="tag-editor">${technologies.map((technology, index) => `<span class="tag-editor__tag" draggable="true" data-draggable-technology="true" data-section-id="${section.id}" data-item-id="${item.id}" data-technology-index="${index}">${escapeHtml(technology.text)}<button type="button" data-action="move-technology-up" data-section-id="${section.id}" data-item-id="${item.id}" data-technology-index="${index}" ${index === 0 ? "disabled" : ""} aria-label="Mover tecnologia para esquerda">←</button><button type="button" data-action="move-technology-down" data-section-id="${section.id}" data-item-id="${item.id}" data-technology-index="${index}" ${index === technologies.length - 1 ? "disabled" : ""} aria-label="Mover tecnologia para direita">→</button><button type="button" data-action="delete-technology" data-section-id="${section.id}" data-item-id="${item.id}" data-technology-index="${index}" aria-label="Excluir ${escapeHtml(technology.text)}">×</button></span>`).join("")}</div></div>` : "";
  const activityItems = section.type === "experience" && Array.isArray(item.activities) ? `<div class="item-custom-fields"><strong>Atividades</strong>${item.activities.map((activity, index) => `<div class="custom-field-editor" draggable="true" data-draggable-activity="true" data-section-id="${section.id}" data-item-id="${item.id}" data-activity-id="${activity.id}"><span>${escapeHtml(activity.text)}</span><button type="button" data-action="move-activity-up" data-section-id="${section.id}" data-item-id="${item.id}" data-activity-id="${activity.id}" ${index === 0 ? "disabled" : ""} aria-label="Mover atividade para cima">↑</button><button type="button" data-action="move-activity-down" data-section-id="${section.id}" data-item-id="${item.id}" data-activity-id="${activity.id}" ${index === item.activities.length - 1 ? "disabled" : ""} aria-label="Mover atividade para baixo">↓</button><button type="button" data-action="duplicate-activity" data-section-id="${section.id}" data-item-id="${item.id}" data-activity-id="${activity.id}">Duplicar</button><button type="button" data-action="delete-activity" data-section-id="${section.id}" data-item-id="${item.id}" data-activity-id="${activity.id}">Excluir</button></div>`).join("")}</div>` : "";
  const imageControls = section.type === "projects" && item.images?.length ? `<div class="item-custom-fields"><strong>Imagens</strong>${item.images.map((image, index) => `<div class="project-image-control"><img src="${escapeHtml(image)}" alt="Miniatura ${index + 1}"><button type="button" data-action="move-project-image-up" data-section-id="${section.id}" data-item-id="${item.id}" data-image-index="${index}" ${index === 0 ? "disabled" : ""}>↑</button><button type="button" data-action="move-project-image-down" data-section-id="${section.id}" data-item-id="${item.id}" data-image-index="${index}" ${index === item.images.length - 1 ? "disabled" : ""}>↓</button><button type="button" data-action="remove-project-image" data-section-id="${section.id}" data-item-id="${item.id}" data-image-index="${index}">Excluir</button></div>`).join("")}</div>` : "";
  return `${techControls}${activityItems}${imageControls}`;
}

function skillsEditor(section) {
  return `<p class="placeholder-note">Níveis visuais são opcionais e podem não ser recomendados em todos os processos seletivos.</p>${editableItems(section)}`;
}

function customFieldsEditor(section) {
  const fields = section.customFields || [];
  const rows = fields.map((field, index) => {
    const id = `${section.id}-${field.id}`;
    const type = field.type === "longtext" ? "textarea" : field.type === "checkbox" ? "checkbox" : field.type === "number" ? "number" : field.type === "date" ? "month" : field.type === "email" ? "email" : field.type === "phone" ? "tel" : field.type === "link" ? "url" : "text";
    const control = type === "textarea"
      ? `<textarea id="${id}" data-section-id="${section.id}" data-custom-field-id="${field.id}">${escapeHtml(field.value || "")}</textarea>`
      : type === "checkbox"
        ? `<input id="${id}" type="checkbox" data-section-id="${section.id}" data-custom-field-id="${field.id}" ${field.value ? "checked" : ""}>`
        : `<input id="${id}" type="${type}" data-section-id="${section.id}" data-custom-field-id="${field.id}" value="${escapeHtml(field.value || "")}">`;
    return `<div class="custom-field-editor"><div class="custom-field-editor__top"><label for="${id}">${escapeHtml(field.label)}</label><span>${escapeHtml(field.type)}</span><button type="button" data-action="move-custom-field-up" data-section-id="${section.id}" data-custom-field-id="${field.id}" ${index === 0 ? "disabled" : ""}>↑</button><button type="button" data-action="move-custom-field-down" data-section-id="${section.id}" data-custom-field-id="${field.id}" ${index === fields.length - 1 ? "disabled" : ""}>↓</button><button type="button" data-action="duplicate-custom-field" data-section-id="${section.id}" data-custom-field-id="${field.id}">Duplicar</button><button type="button" data-action="toggle-custom-field" data-section-id="${section.id}" data-custom-field-id="${field.id}">${field.visible ? "Ocultar" : "Exibir"}</button><button type="button" class="section-tools__danger" data-action="delete-custom-field" data-section-id="${section.id}" data-custom-field-id="${field.id}">Excluir</button></div>${control}</div>`;
  }).join("");
  return `<div class="custom-fields"><div class="custom-fields__heading"><strong>Campos personalizados</strong><button type="button" data-action="add-custom-field" data-section-id="${section.id}">+ Novo campo</button></div>${rows || `<p class="empty-editor-state">Nenhum campo personalizado nesta categoria.</p>`}</div>`;
}

function contentFields(section) {
  const item = section.items[0] || {};
  let content = "";
  if (section.type === "header") content = `<div class="field-row"><div class="field"><label for="name">Nome completo</label><input id="name" data-path="header.name" value="${escapeHtml(item.name || "")}"></div><div class="field"><label for="role">Cargo pretendido</label><input id="role" data-path="header.role" value="${escapeHtml(item.role || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="email">E-mail</label><input id="email" type="email" data-path="header.email" value="${escapeHtml(item.email || "")}"></div><div class="field"><label for="phone">Telefone</label><input id="phone" data-path="header.phone" value="${escapeHtml(item.phone || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="city">Cidade</label><input id="city" data-path="header.city" value="${escapeHtml(item.city || "")}"></div><div class="field"><label for="photo">Foto (opcional)</label><input id="photo" type="file" accept="image/*" data-photo-input></div></div>
    <div class="field-row"><div class="field"><label for="linkedin">LinkedIn</label><input id="linkedin" data-path="header.linkedin" value="${escapeHtml(item.linkedin || "")}"></div><div class="field"><label for="github">GitHub</label><input id="github" data-path="header.github" value="${escapeHtml(item.github || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="portfolio">Portfólio</label><input id="portfolio" data-path="header.portfolio" value="${escapeHtml(item.portfolio || "")}"></div><div class="field"><label for="birthdate">Data de nascimento</label><input id="birthdate" type="date" data-path="header.birthdate" value="${escapeHtml(item.birthdate || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="whatsapp">WhatsApp</label><input id="whatsapp" data-path="header.whatsapp" value="${escapeHtml(item.whatsapp || "")}"></div><div class="field"><label for="state">Estado</label><input id="state" data-path="header.state" value="${escapeHtml(item.state || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="country">País</label><input id="country" data-path="header.country" value="${escapeHtml(item.country || "")}"></div><div class="field"><label for="nationality">Nacionalidade</label><input id="nationality" data-path="header.nationality" value="${escapeHtml(item.nationality || "")}"></div></div>
    <div class="field-row"><div class="field"><label for="site">Site</label><input id="site" data-path="header.site" value="${escapeHtml(item.site || "")}"></div><div class="field"><label for="custom-link">Link personalizado</label><input id="custom-link" data-path="header.customLink" value="${escapeHtml(item.customLink || "")}"></div></div>
    <fieldset class="section-settings"><legend>Foto</legend><label>Formato<select data-header-photo-setting="shape"><option value="round">Redonda</option><option value="square">Quadrada</option></select></label><label>Tamanho <input type="range" min="48" max="140" value="${item.photoSettings?.size || 84}" data-header-photo-setting="size"></label><label>Espessura da borda <input type="range" min="0" max="8" value="${item.photoSettings?.borderWidth || 0}" data-header-photo-setting="borderWidth"></label><label>Cor da borda <input type="color" value="${item.photoSettings?.borderColor || "#2f6db1"}" data-header-photo-setting="borderColor"></label><label>Posição<select data-header-photo-setting="position"><option value="right">Direita</option><option value="left">Esquerda</option><option value="center">Centro</option></select></label>${item.photo ? `<button type="button" data-action="remove-photo">Remover foto</button>` : ""}</fieldset>
    <fieldset class="section-settings"><legend>Exibir no cabeçalho</legend>${["name","role","photo","email","phone","whatsapp","city","state","country","nationality","birthdate","linkedin","github","portfolio","site","customLink"].map((key) => `<label><input type="checkbox" data-header-visibility="${key}" ${item.visibleFields?.[key] !== false ? "checked" : ""}> ${key}</label>`).join("")}</fieldset>`;
  else if (section.type === "summary") content = `<div class="field"><label for="summary">Apresentação profissional</label><textarea id="summary" data-path="summary.text" data-summary-input>${escapeHtml(item.text || "")}</textarea><small data-summary-count>${(item.text || "").length} caracteres</small></div>`;
  else if (section.type === "skills") content = skillsEditor(section);
  else content = editableItems(section);
  return `${content}${customFieldsEditor(section)}`;
}

function sectionSettings(section) {
  if (section.type === "summary") return `<div class="section-settings"><label><input type="checkbox" data-section-setting="showTitle" data-section-id="${section.id}" ${section.settings.showTitle !== false ? "checked" : ""}> Exibir título na prévia</label></div>`;
  if (section.type === "skills") return `<div class="section-settings"><label>Exibição<select data-section-setting="display" data-section-id="${section.id}"><option value="tags">Tags</option><option value="list">Lista</option><option value="bars">Barras</option><option value="stars">Estrelas</option><option value="dots">Bolinhas</option></select></label></div>`;
  return "";
}

function contentPanel(state) {
  return `<div class="section-actions"><button class="create-section-button" type="button" data-action="create-section">+ Criar categoria</button><p>Organize cada bloco do seu currículo sem perder o conteúdo.</p></div>${state.sections.map((section, index) => `<section class="section-card ${index < 2 ? "is-open" : ""}" data-section-card="${section.id}" draggable="true">
    <button class="section-card__header" type="button" data-action="toggle-section" aria-expanded="${index < 2}">
      <span class="section-card__icon" aria-hidden="true">${iconLabels[section.type] || "SE"}</span><strong>${escapeHtml(section.title)}</strong><small>${section.items.length} ${section.items.length === 1 ? "item" : "itens"}</small><span class="section-card__chevron" aria-hidden="true">⌃</span>
    </button><div class="section-card__body"><div class="section-tools" aria-label="Ações de ${escapeHtml(section.title)}">
      <button type="button" data-action="rename-section" data-section-id="${section.id}">Renomear</button>
      <button type="button" data-action="toggle-visibility" data-section-id="${section.id}">${section.visible ? "Ocultar" : "Exibir"}</button>
      <button type="button" data-action="duplicate-section" data-section-id="${section.id}">Duplicar</button>
      <button type="button" data-action="move-section-up" data-section-id="${section.id}" ${index === 0 ? "disabled" : ""}>↑</button>
      <button type="button" data-action="move-section-down" data-section-id="${section.id}" ${index === state.sections.length - 1 ? "disabled" : ""}>↓</button>
      ${section.type !== "header" ? `<button type="button" data-action="move-section-column" data-section-id="${section.id}">Coluna ${section.column === 1 ? "2" : "1"}</button>` : ""}
      ${section.type !== "header" ? `<button type="button" class="section-tools__danger" data-action="delete-section" data-section-id="${section.id}">Excluir</button>` : ""}
    </div>${!section.visible ? `<p class="section-hidden-note">Este bloco está oculto na prévia e no PDF.</p>` : ""}${sectionSettings(section)}${contentFields(section)}</div></section>`).join("")}`;
}

function stylePanel(state) {
  return `<div class="theme-card"><h3>Paletas</h3><div class="palette-actions"><button type="button" data-action="apply-palette" data-palette="marinho">Azul marinho</button><button type="button" data-action="apply-palette" data-palette="grafite">Cinza escuro</button><button type="button" data-action="apply-palette" data-palette="preto">Preto e branco</button><button type="button" data-action="apply-palette" data-palette="verde">Verde esmeralda</button><button type="button" data-action="apply-palette" data-palette="roxo">Roxo moderno</button><button type="button" data-action="apply-palette" data-palette="laranja">Laranja</button><button type="button" data-action="apply-palette" data-palette="eletrico">Azul elétrico</button><button type="button" data-action="apply-palette" data-palette="vinho">Vinho</button><button type="button" data-action="apply-palette" data-palette="pastel">Pastel minimalista</button></div><small>Paletas mantêm o texto neutro e aplicam cor aos destaques.</small></div><div class="theme-card"><h3>Cores e contraste</h3><div class="field-row"><label>Primária (HEX)<input type="text" value="${state.theme.accentColor}" data-theme="accentColor" pattern="^#[0-9A-Fa-f]{6}$"></label><label>Títulos (HEX)<input type="text" value="${state.theme.titleColor}" data-theme="titleColor" pattern="^#[0-9A-Fa-f]{6}$"></label><label>Texto (HEX)<input type="text" value="${state.theme.textColor}" data-theme="textColor" pattern="^#[0-9A-Fa-f]{6}$"></label></div><label>Contraste<select data-theme="contrastMode"><option value="light">Fundo claro</option><option value="darkHeader">Cabeçalho escuro</option></select></label><label>Intensidade<select data-theme="colorIntensity"><option value="soft">Suave</option><option value="solid">Sólida</option></select></label></div><div class="theme-card"><h3>Tipografia</h3><div class="field"><label for="font-family">Fonte</label><select id="font-family" data-theme="fontFamily"><optgroup label="Sans-serif"><option value="Inter, Arial, sans-serif">Inter</option><option value="Roboto, Arial, sans-serif">Roboto</option><option value="Montserrat, Arial, sans-serif">Montserrat</option><option value="Arial, sans-serif">Arial</option></optgroup><optgroup label="Serif"><option value="Merriweather, Georgia, serif">Merriweather</option><option value="Georgia, serif">Georgia</option></optgroup><optgroup label="Criativa"><option value="Trebuchet MS, sans-serif">Trebuchet</option></optgroup></select></div><div class="field"><label for="font-size">Tamanho base: ${state.theme.fontSize}px</label><input id="font-size" type="range" min="10" max="18" value="${state.theme.fontSize}" data-theme="fontSize"></div><div class="field"><label for="line-height">Altura da linha: ${state.theme.lineHeight}</label><input id="line-height" type="range" min="1.1" max="2" step=".1" value="${state.theme.lineHeight}" data-theme="lineHeight"></div></div>
  <div class="theme-card"><h3>Cores e acabamento</h3><div class="field-row"><div class="field"><label for="accent-color">Destaque</label><input id="accent-color" type="color" value="${state.theme.accentColor}" data-theme="accentColor"></div><div class="field"><label for="title-color">Títulos</label><input id="title-color" type="color" value="${state.theme.titleColor}" data-theme="titleColor"></div><div class="field"><label for="text-color">Texto</label><input id="text-color" type="color" value="${state.theme.textColor}" data-theme="textColor"></div><div class="field"><label for="background-color">Fundo</label><input id="background-color" type="color" value="${state.theme.backgroundColor}" data-theme="backgroundColor"></div></div><div class="field"><label>Tamanho dos títulos: ${state.theme.titleSize || 12}px</label><input type="range" min="10" max="24" value="${state.theme.titleSize || 12}" data-theme="titleSize"></div><div class="field"><label for="title-weight">Peso dos títulos</label><select id="title-weight" data-theme="titleWeight"><option value="500">Médio</option><option value="700">Negrito</option><option value="800">Extra negrito</option></select></div><div class="field"><label for="title-transform">Transformação</label><select id="title-transform" data-theme="titleTransform"><option value="uppercase">MAIÚSCULAS</option><option value="none">Normal</option></select></div><div class="field"><label>Raio das bordas: ${state.theme.borderRadius}px</label><input type="range" min="0" max="24" value="${state.theme.borderRadius}" data-theme="borderRadius"></div><label><input type="checkbox" data-theme="showDividers" ${state.theme.showDividers !== false ? "checked" : ""}> Exibir divisórias</label></div>`;
}

function layoutPanel(state) {
  return `<div class="theme-card"><h3>Estrutura da página</h3><div class="field"><label for="columns">Número de colunas</label><select id="columns" data-layout="columns"><option value="1" ${state.layout.columns === 1 ? "selected" : ""}>Uma coluna</option><option value="2" ${state.layout.columns === 2 ? "selected" : ""}>Duas colunas</option></select></div><div class="field"><label for="ratio">Proporção das colunas</label><select id="ratio" data-layout="columnRatio"><option value="35-65">35 / 65</option><option value="50-50">50 / 50</option><option value="40-60">40 / 60</option><option value="30-70">30 / 70</option><option value="60-40">60 / 40</option><option value="65-35">65 / 35</option><option value="70-30">70 / 30</option></select></div><div class="field"><label for="page-padding">Margens internas: ${state.theme.pagePadding} mm</label><input id="page-padding" type="range" min="10" max="30" value="${state.theme.pagePadding}" data-theme="pagePadding"></div></div>`;
}

export function renderEditor(state, activeTab = "content") {
  const target = document.querySelector("#editor-content");
  target.innerHTML = activeTab === "style" ? stylePanel(state) : activeTab === "layout" ? layoutPanel(state) : contentPanel(state);
  target.querySelectorAll(".section-card").forEach((card) => { card.draggable = false; const header = card.querySelector(".section-card__header"); if (header) { header.draggable = true; header.title = "Arraste para mover a categoria"; } });
  target.querySelectorAll("[data-draggable-item]").forEach((item) => { item.draggable = false; const heading = item.querySelector(".item-editor__heading"); if (heading) { heading.draggable = true; heading.title = "Arraste para mover este item"; } });
  if (activeTab === "style") { target.querySelectorAll('input[type="text"][data-theme]').forEach((input) => input.closest("label")?.remove()); const contrastTitle = [...target.querySelectorAll(".theme-card h3")].find((title) => title.textContent === "Cores e contraste"); if (contrastTitle) contrastTitle.textContent = "Contraste"; const palette = target.querySelector(".palette-actions"); if (palette) { [["vermelho", "Vermelho"], ["analista", "Azul Analista"]].forEach(([value, label]) => { const button = document.createElement("button"); button.type = "button"; button.dataset.action = "apply-palette"; button.dataset.palette = value; button.setAttribute("aria-label", `Paleta ${label}`); button.title = label; button.textContent = label; palette.append(button); }); } const hierarchy = document.createElement("div"); hierarchy.className = "theme-card theme-card--colors"; hierarchy.innerHTML = `<h3>Cores por hierarquia</h3><p>Escolha uma cor global para cada tipo de informação.</p><div class="color-picker-grid"><label>Subtítulos<input type="color" value="${state.theme.subtitleColor || state.theme.accentColor}" data-theme="subtitleColor"></label><label>Texto menor<input type="color" value="${state.theme.mutedColor || "#6b7789"}" data-theme="mutedColor"></label><label>Links<input type="color" value="${state.theme.linkColor || state.theme.accentColor}" data-theme="linkColor"></label><label>Divisores<input type="color" value="${state.theme.dividerColor || "#cfdae7"}" data-theme="dividerColor"></label></div></div>`; target.append(hierarchy); }
  if (activeTab === "style") { const template = document.createElement("div"); const selected = state.theme.template || "original"; const buttonClass = (name) => `button ${selected === name ? "button--primary" : "button--ghost"}`; template.className = "theme-card template-card"; template.innerHTML = `<h3>Modelos visuais</h3><p>Cada modelo possui composição, densidade e hierarquia próprias. Seu conteúdo permanece intacto.</p><div class="template-card__actions"><button type="button" class="${buttonClass("original")}" data-action="apply-original-template">Original</button><button type="button" class="${buttonClass("analyst")}" data-action="apply-analyst-template">Analista</button><button type="button" class="${buttonClass("sidebar")}" data-action="apply-sidebar-template">Barra lateral</button><button type="button" class="${buttonClass("sidebar-right")}" data-action="apply-executive-template">Executivo</button><button type="button" class="${buttonClass("compact")}" data-action="apply-compact-template">Compacto</button></div><label class="template-card__color">Cor da Barra lateral, Executivo e Compacto <input type="color" value="${state.theme.sidebarColor || "#173a5a"}" data-theme="sidebarColor" aria-label="Mudar a cor dos modelos com painel ou cabeçalho colorido"></label>`; target.prepend(template); }
  if (activeTab === "style") { const contrastCard = [...target.querySelectorAll(".theme-card")].find((card) => card.querySelector("h3")?.textContent === "Contraste"); contrastCard?.querySelector(".field-row")?.remove(); contrastCard?.classList.add("theme-card--contrast"); contrastCard?.querySelectorAll(":scope > label").forEach((label) => { const select = label.querySelector("select"); if (!select) return; const text = [...label.childNodes].filter((node) => node.nodeType === Node.TEXT_NODE).map((node) => node.textContent.trim()).join(""); label.textContent = ""; const caption = document.createElement("span"); caption.className = "contrast-control__label"; caption.textContent = text; label.append(caption, select); }); }
  const fontSelect = target.querySelector('[data-theme="fontFamily"]');
  if (fontSelect) fontSelect.value = state.theme.fontFamily;
  if (fontSelect) { const card = fontSelect.closest(".theme-card"); const picker = document.createElement("div"); picker.className = "font-picker"; picker.innerHTML = `<button type="button" class="font-picker__trigger" data-action="toggle-font-picker" aria-expanded="false" aria-haspopup="listbox">${fontSelect.options[fontSelect.selectedIndex]?.text || "Fonte"}<span>⌄</span></button><div class="font-picker__menu" role="listbox" tabindex="-1" hidden>${[...fontSelect.options].map((option) => `<button type="button" role="option" aria-selected="${option.value === state.theme.fontFamily}" data-action="select-font" data-font-value="${escapeHtml(option.value)}" style="font-family:${escapeHtml(option.value)}">${escapeHtml(option.text)}</button>`).join("")}</div><div class="font-preview"><small>Prévia da fonte</small><strong>Seu currículo profissional</strong><span>Experiência e formação em destaque.</span></div>`; picker.querySelector(".font-preview").style.fontFamily = state.theme.fontFamily; fontSelect.hidden = true; fontSelect.after(picker); card?.querySelector("label[for='font-family']")?.classList.add("font-picker__label"); }
  target.querySelectorAll("select[data-theme]").forEach((node) => { if (state.theme[node.dataset.theme] != null) node.value = state.theme[node.dataset.theme]; });
  const ratioSelect = target.querySelector('[data-layout="columnRatio"]');
  if (ratioSelect) ratioSelect.value = state.layout.columnRatio;
  const header = state.sections.find((section) => section.type === "header")?.items[0];
  target.querySelectorAll("[data-header-photo-setting]").forEach((node) => { node.value = header?.photoSettings?.[node.dataset.headerPhotoSetting] ?? node.value; });
  const birthdayInput = target.querySelector("#birthdate");
  if (birthdayInput) { const [year = "", month = "", day = ""] = String(header?.birthdate || "").split("-"); const months = ["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"]; const picker = document.createElement("details"); picker.className = "birthday-picker"; picker.innerHTML = `<summary>Data de nascimento${day ? `: ${day}/${month}/${year}` : ""}</summary><div class="birthday-picker__body"><div class="birthday-picker__days">${Array.from({ length: 31 }, (_, index) => `<button type="button" data-action="select-birthday-day" data-day="${String(index + 1).padStart(2,"0")}" class="${day === String(index + 1).padStart(2,"0") ? "is-selected" : ""}">${index + 1}</button>`).join("")}</div><div class="birthday-picker__bottom"><details class="birthday-picker__month-menu"><summary>${months[Number(month) - 1] || "Escolher mês"}</summary><div class="birthday-picker__months">${months.map((name, index) => `<button type="button" data-action="select-birthday-month" data-month="${String(index + 1).padStart(2,"0")}" class="${month === String(index + 1).padStart(2,"0") ? "is-selected" : ""}">${name}</button>`).join("")}</div></details><input data-birthday-year inputmode="numeric" placeholder="Ano (ex. 1995)" value="${year}"></div><button type="button" class="birthday-picker__apply" data-action="apply-birthday">Aplicar data</button></div>`; birthdayInput.hidden = true; birthdayInput.closest(".field")?.append(picker); }
  const headerLabels = { name: "Nome", role: "Cargo", photo: "Foto", email: "E-mail", phone: "Telefone", whatsapp: "WhatsApp", city: "Cidade", state: "Estado", country: "País", nationality: "Nacionalidade", birthdate: "Data de nascimento", linkedin: "LinkedIn", github: "GitHub", portfolio: "Portfólio", site: "Site", customLink: "Link personalizado" };
  target.querySelectorAll("[data-header-visibility]").forEach((input) => { const label = input.closest("label"); if (!label) return; label.textContent = headerLabels[input.dataset.headerVisibility] || input.dataset.headerVisibility; label.append(input); label.closest("fieldset")?.classList.add("header-visibility-list"); });
  target.querySelectorAll("[data-section-setting]").forEach((node) => { const section = state.sections.find((entry) => entry.id === node.dataset.sectionId); if (node.type === "checkbox") node.checked = section?.settings?.[node.dataset.sectionSetting] !== false; else if (section?.settings?.[node.dataset.sectionSetting] != null) node.value = section.settings[node.dataset.sectionSetting]; });
  target.querySelectorAll('[data-action="move-section-up"], [data-action="move-item-up"]').forEach((button) => { button.title = "Mover para cima"; button.setAttribute("aria-label", "Mover para cima"); });
  target.querySelectorAll('[data-action="move-section-down"], [data-action="move-item-down"]').forEach((button) => { button.title = "Mover para baixo"; button.setAttribute("aria-label", "Mover para baixo"); });
}
